$(document).ready(function(){
	defaultTarget();
//	search();
});

var target = "";
var endpoint = "http://dbpedia.org/sparql";
//var query = "select * {?s ?p ?o} limit 3";
//var query = "select  ?a ?k ?w { ?a foaf:name \"Leonardo da Vinci\"@en. optional{?a dbp:knownFor ?k; dbp:notableWorks ?w .}} limit 1 " ;
var ask = "ASK {?a foaf:name \"Leonardo da Vinci\"@en . ?a rdf:type foaf:Person .}";

function defaultTarget(){
	var targets = ["Leonardo da Vinci","Paris","911"];
	
	$('#te').html("Example: <a href='' onclick=\"return setSearch('"+targets[0]+"')\"> " + targets[0] + "</a>");
	$('#te1').html("Example: <a href='' onclick=\"return setSearch('"+targets[1]+"')\"> " + targets[1] + "</a>");
//	$('#te2').html("Example: <a href='' onclick=\"return setSearch('"+targets[2]+"')\"> " + targets[2] + "</a>");

};


function setSearch(target){
	document.getElementById("target").value = target;
	targetSearch();
	return false;
};

function targetSearch(){
	target = $('#target').val();
	if(target == "") {
		document.getElementById("question").innerHTML = "please input the target you want to generate question about."; 
	}else if(target == "Paris" || target == "London"|| target == "New York City"){
			var query = "select distinct ?a ?cn ?sd ?pic ?p ?ab ?pn { ?a foaf:name \""+target+"\"@en; rdf:type dbo:Place ; foaf:depiction ?pic.?a dbo:country ?b.?b foaf:name ?cn. ?p dbo:hometown ?a; rdf:type foaf:Person; foaf:name ?pn; dbp:shortDescription ?sd .optional{?a dbo:abstract ?ab.FILTER(LANG(?ab)=\"en\")}} ORDER BY ?ab LIMIT 1";

			sparqlQueryJson(query, endpoint, myCallbackPlace, false);
			}else /*if(target != "Paris" && target != "London")*/{		
		//callback for Person
		var query = "select DISTINCT ?a ?ab ?sd ?pic ?nw ?kf ?d1 ?d2 ?p1 ?p2{ ?a foaf:name \""+target+"\"@en ; dbp:shortDescription ?sd;foaf:depiction ?pic ;dbp:dateOfBirth ?d1; dbo:abstract ?ab ; dbp:placeOfBirth  ?p1. optional{ ?a  dbp:dateOfDeath ?d2;dbp:placeOfDeath ?p2 .} optional{?a dbp:notableWorks ?nw .} optional{?a dbp:knownFor ?kf .}  FILTER (LANG(?ab) = \"en\")} limit 1";
		sparqlQueryJson(query, endpoint, myCallback, false);
 		}
};

function sparqlQueryJson(queryStr, endpoint, callback, isDebug) {
	var querypart = "query=" + escape(queryStr);
    
      // Get our HTTP request object.
	var xmlhttp = null;
    if(window.XMLHttpRequest) {
    	xmlhttp = new XMLHttpRequest();
    }else if(window.ActiveXObject) {
       // Code for older versions of IE, like IE6 and before.
  			xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
			}else {
       			alert('The browser does not support XMLHttpRequests');
     		}
    
     // Set up a POST with JSON result format.
	xmlhttp.open('post', endpoint, false); // GET can have caching probs, so POST
	xmlhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
	xmlhttp.setRequestHeader("Accept", "application/sparql-results+json");
    
     // Set up callback to get the response asynchronously.
    xmlhttp.onreadystatechange = function() {
      if(xmlhttp.readyState == 4) {
        if(xmlhttp.status == 200) {
           // Do something with the results
           if(isDebug) alert(xmlhttp.responseText); 
               callback(xmlhttp.responseText);  
         } else {
           // Some kind of error occurred.
           alert("Sparql query error: " + xmlhttp.status + " "
               + xmlhttp.responseText);
         }
       }
     };
     // Send the query to the endpoint.
     xmlhttp.send(querypart);
    
     // Done; now just wait for the callback to be called.
};

function myCallback(str) {
        // Convert result to JSON
	var jsonObj = eval('(' + str + ')');
	
        // Build up a table of results
		document.getElementById("abstract").innerHTML = "";
		if(jsonObj.results.bindings[0].ab) 	document.getElementById("abstract").innerHTML = jsonObj.results.bindings[0].ab.value;
		
	 var question = "who is the person, a " + jsonObj.results.bindings[0].sd.value+", was born in " + jsonObj.results.bindings[0].p1.value+ " in the date of " + jsonObj.results.bindings[0].d1.value ;
	 if( jsonObj.results.bindings[0].p2) {
		 question = question  + " and was died in " + jsonObj.results.bindings[0].p2.value + " on " + jsonObj.results.bindings[0].d2.value + " .";
		 }
		 
	 question = "<p>natural language question generated by Linked Open Data from DBpedia: <br> <br> <p colour='red'>" + question +"</p>";
	 document.getElementById("naturalquestion").innerHTML = question;
	 if(jsonObj.results.bindings[0].pic) {document.getElementById("img").innerHTML = "<img src='" +  jsonObj.results.bindings[0].pic.value + "'width='400' height='500'>";}else{document.getElementById("img").innerHTML = "<p></p>";}
	 
	 var who = "";
	 if(jsonObj.results.bindings[0].nw)
		who = "who was the creator of " + jsonObj.results.bindings[0].nw.value + " ?" +" <br> Answer : " + target +"<br>";
	 var what ="";
	 if(jsonObj.results.bindings[0].kf)
	 	what = "what does " + target + " known for ?" + " <br> Answer : " + jsonObj.results.bindings[0].kf.value + "<br>";
	 var when = "when was " + target + " born ?" + "<br> Answer : " + jsonObj.results.bindings[0].d1.value + "<br>" ;
	 var where = "where was " + target + " from ?" + "<br> Answer : " + jsonObj.results.bindings[0].p1.value + "<br>"; 
	 document.getElementById("specificquestion").innerHTML = who + "<br>" + what + "<br>"+ when + "<br>" + where;
	  
};

function myCallbackPlace(str) {
        // Convert result to JSON
	var jsonObj = eval('(' + str + ')');
	
        // Build up a table of results
	document.getElementById("abstract").innerHTML = "";
	if(jsonObj.results.bindings[0].ab) 	document.getElementById("abstract").innerHTML = jsonObj.results.bindings[0].ab.value;
	 
	var question = "where is there in the picture, the city of " + jsonObj.results.bindings[0].cn.value;
	  
	 question = "<p>natural language question generated by Linked Open Data from DBpedia: <br> <br> <p colour='red'>" + question +"</p>";
	 document.getElementById("naturalquestion").innerHTML = question;
	 
	 if(jsonObj.results.bindings[0].pic) {document.getElementById("img").innerHTML = "<img src='" +  jsonObj.results.bindings[0].pic.value + "'width='400' height='500'>";}else{document.getElementById("img").innerHTML = "<p></p>";}
	 
	 var where = "";
	 if(jsonObj.results.bindings[0].p)
		where = "where is the hometown of " + jsonObj.results.bindings[0].pn.value + " ("+jsonObj.results.bindings[0].sd.value+") ?" +" <br> Answer : " + target +"<br>";
	 document.getElementById("specificquestion").innerHTML = where + "<br>" ;
	  
};